name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'refactor'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
autolabeler:
  - label: feat
    branch:
      - '/^feat[/-].+/'
    title:
      - '/^feat:.+/'
  - label: fix
    branch:
      - '/^fix[/-].+/'
    title:
      - '/^fix:.+/'
  - label: refactor
    branch:
      - '/^refactor[/-].+/'
    title:
      - '/^refactor:.+/'
  - label: chore
    branch:
      - '/^chore[/-].+/'
    title:
      - '/^chore:.+/'
      - '/^chore\(deps\):.+/'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
