// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"net/http"

	"github.com/Pranc1ngPegasus/trial-field/adapter/handler"
	"github.com/Pranc1ngPegasus/trial-field/adapter/resolver"
	"github.com/Pranc1ngPegasus/trial-field/adapter/server"
	logger2 "github.com/Pranc1ngPegasus/trial-field/domain/logger"
	tracer2 "github.com/Pranc1ngPegasus/trial-field/domain/tracer"
	"github.com/Pranc1ngPegasus/trial-field/infra/configuration"
	"github.com/Pranc1ngPegasus/trial-field/infra/logger"
	"github.com/Pranc1ngPegasus/trial-field/infra/tracer"
)

// Injectors from wire.go:

func initialize() (*app, error) {
	loggerLogger, err := logger.NewLogger()
	if err != nil {
		return nil, err
	}
	contextContext := context.Background()
	configurationConfiguration, err := configuration.NewConfiguration(contextContext, loggerLogger)
	if err != nil {
		return nil, err
	}
	tracerTracer, err := tracer.NewTracer(loggerLogger, configurationConfiguration)
	if err != nil {
		return nil, err
	}
	executableSchema := resolver.NewSchema()
	handlerHandler := handler.NewHandler(loggerLogger, executableSchema)
	httpServer := server.NewServer(contextContext, loggerLogger, configurationConfiguration, handlerHandler)
	mainApp := &app{
		logger: loggerLogger,
		tracer: tracerTracer,
		server: httpServer,
	}
	return mainApp, nil
}

// wire.go:

type app struct {
	logger logger2.Logger
	tracer tracer2.Tracer
	server *http.Server
}
