name: Docker
on:
  pull_request:
    paths:
      - Dockerfile
jobs:
  hadolint:
    name: Dockerfile lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
        with:
          reporter: github-pr-review
          hadolint_flags: Dockerfile
