name: Trivy
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  trivy:
    name: Security check
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: docker.io/pranc1ngpegasus/go-template
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build an image from Dockerfile
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
